/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResponsaveisRouteImport } from './routes/responsaveis'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as InteracoesRouteImport } from './routes/interacoes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as Entregas_prazosRouteImport } from './routes/entregas_prazos'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresasIdRouteImport } from './routes/empresas.$id'

const ResponsaveisRoute = ResponsaveisRouteImport.update({
  id: '/responsaveis',
  path: '/responsaveis',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const InteracoesRoute = InteracoesRouteImport.update({
  id: '/interacoes',
  path: '/interacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const Entregas_prazosRoute = Entregas_prazosRouteImport.update({
  id: '/entregas_prazos',
  path: '/entregas_prazos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIdRoute = EmpresasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmpresasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/entregas_prazos': typeof Entregas_prazosRoute
  '/financeiro': typeof FinanceiroRoute
  '/interacoes': typeof InteracoesRoute
  '/pendencias': typeof PendenciasRoute
  '/responsaveis': typeof ResponsaveisRoute
  '/empresas/$id': typeof EmpresasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/entregas_prazos': typeof Entregas_prazosRoute
  '/financeiro': typeof FinanceiroRoute
  '/interacoes': typeof InteracoesRoute
  '/pendencias': typeof PendenciasRoute
  '/responsaveis': typeof ResponsaveisRoute
  '/empresas/$id': typeof EmpresasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/entregas_prazos': typeof Entregas_prazosRoute
  '/financeiro': typeof FinanceiroRoute
  '/interacoes': typeof InteracoesRoute
  '/pendencias': typeof PendenciasRoute
  '/responsaveis': typeof ResponsaveisRoute
  '/empresas/$id': typeof EmpresasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/empresas'
    | '/entregas_prazos'
    | '/financeiro'
    | '/interacoes'
    | '/pendencias'
    | '/responsaveis'
    | '/empresas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/empresas'
    | '/entregas_prazos'
    | '/financeiro'
    | '/interacoes'
    | '/pendencias'
    | '/responsaveis'
    | '/empresas/$id'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/empresas'
    | '/entregas_prazos'
    | '/financeiro'
    | '/interacoes'
    | '/pendencias'
    | '/responsaveis'
    | '/empresas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContratosRoute: typeof ContratosRoute
  DashboardRoute: typeof DashboardRoute
  EmpresasRoute: typeof EmpresasRouteWithChildren
  Entregas_prazosRoute: typeof Entregas_prazosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  InteracoesRoute: typeof InteracoesRoute
  PendenciasRoute: typeof PendenciasRoute
  ResponsaveisRoute: typeof ResponsaveisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/responsaveis': {
      id: '/responsaveis'
      path: '/responsaveis'
      fullPath: '/responsaveis'
      preLoaderRoute: typeof ResponsaveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interacoes': {
      id: '/interacoes'
      path: '/interacoes'
      fullPath: '/interacoes'
      preLoaderRoute: typeof InteracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas_prazos': {
      id: '/entregas_prazos'
      path: '/entregas_prazos'
      fullPath: '/entregas_prazos'
      preLoaderRoute: typeof Entregas_prazosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/$id': {
      id: '/empresas/$id'
      path: '/$id'
      fullPath: '/empresas/$id'
      preLoaderRoute: typeof EmpresasIdRouteImport
      parentRoute: typeof EmpresasRoute
    }
  }
}

interface EmpresasRouteChildren {
  EmpresasIdRoute: typeof EmpresasIdRoute
}

const EmpresasRouteChildren: EmpresasRouteChildren = {
  EmpresasIdRoute: EmpresasIdRoute,
}

const EmpresasRouteWithChildren = EmpresasRoute._addFileChildren(
  EmpresasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContratosRoute: ContratosRoute,
  DashboardRoute: DashboardRoute,
  EmpresasRoute: EmpresasRouteWithChildren,
  Entregas_prazosRoute: Entregas_prazosRoute,
  FinanceiroRoute: FinanceiroRoute,
  InteracoesRoute: InteracoesRoute,
  PendenciasRoute: PendenciasRoute,
  ResponsaveisRoute: ResponsaveisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
